package com.gupao.prototype;

public class UserPersonalEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BHA.T_USER_PERSONAL.ID
     *
     * @mbggenerated Wed Jan 03 10:47:30 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BHA.T_USER_PERSONAL.CRED_TYPE
     *
     * @mbggenerated Wed Jan 03 10:47:30 CST 2018
     */
    private String credType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BHA.T_USER_PERSONAL.CRED_NUM
     *
     * @mbggenerated Wed Jan 03 10:47:30 CST 2018
     */
    private String credNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BHA.T_USER_PERSONAL.IS_OPEN_ONEPASSPORT
     *
     * @mbggenerated Wed Jan 03 10:47:30 CST 2018
     */
    private Boolean isOpenOnepassport;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BHA.T_USER_PERSONAL.ID
     *
     * @return the value of BHA.T_USER_PERSONAL.ID
     *
     * @mbggenerated Wed Jan 03 10:47:30 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BHA.T_USER_PERSONAL.ID
     *
     * @param id the value for BHA.T_USER_PERSONAL.ID
     *
     * @mbggenerated Wed Jan 03 10:47:30 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BHA.T_USER_PERSONAL.CRED_TYPE
     *
     * @return the value of BHA.T_USER_PERSONAL.CRED_TYPE
     *
     * @mbggenerated Wed Jan 03 10:47:30 CST 2018
     */
    public String getCredType() {
        return credType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BHA.T_USER_PERSONAL.CRED_TYPE
     *
     * @param credType the value for BHA.T_USER_PERSONAL.CRED_TYPE
     *
     * @mbggenerated Wed Jan 03 10:47:30 CST 2018
     */
    public void setCredType(String credType) {
        this.credType = credType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BHA.T_USER_PERSONAL.CRED_NUM
     *
     * @return the value of BHA.T_USER_PERSONAL.CRED_NUM
     *
     * @mbggenerated Wed Jan 03 10:47:30 CST 2018
     */
    public String getCredNum() {
        return credNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BHA.T_USER_PERSONAL.CRED_NUM
     *
     * @param credNum the value for BHA.T_USER_PERSONAL.CRED_NUM
     *
     * @mbggenerated Wed Jan 03 10:47:30 CST 2018
     */
    public void setCredNum(String credNum) {
        this.credNum = credNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BHA.T_USER_PERSONAL.IS_OPEN_ONEPASSPORT
     *
     * @return the value of BHA.T_USER_PERSONAL.IS_OPEN_ONEPASSPORT
     *
     * @mbggenerated Wed Jan 03 10:47:30 CST 2018
     */
    public Boolean getIsOpenOnepassport() {
        return isOpenOnepassport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BHA.T_USER_PERSONAL.IS_OPEN_ONEPASSPORT
     *
     * @param isOpenOnepassport the value for BHA.T_USER_PERSONAL.IS_OPEN_ONEPASSPORT
     *
     * @mbggenerated Wed Jan 03 10:47:30 CST 2018
     */
    public void setIsOpenOnepassport(Boolean isOpenOnepassport) {
        this.isOpenOnepassport = isOpenOnepassport;
    }
}